- CMakeLists.txt
- src/Config.cpp
- src/Config.h
- src/GPU2D.cpp
- src/GPU2D.h
- src/GPU3D.cpp
- src/GPU3D.h
- src/GPU3D_Soft.cpp
- src/NDS.cpp
- src/NDS.h
- src/NDSCart.cpp
- src/SPI.cpp
- src/Wifi.h
- src/libretro.cpp
- src/wx/EmuConfig.cpp
- src/wx/EmuConfig.h
- src/wx/Platform.cpp
- src/wx/main.cpp
Update to [melonDS 0.4](http://melonds.kuribo64.net/comments.php?id=28), which is revision [`08bdef481f1685e596fc2e45597a4bfe60aae8aa`](https://github.com/StapleButter/melonDS/commit/08bdef481f1685e596fc2e45597a4bfe60aae8aa).
> Update to MelonDS 0.4

- Makefile
- src/libretro.cpp
This applies the GIT_VERSION pattern to the announced library version.
> Add GIT_VERSION information

- src/libretro/libretro.cpp
This loop is no longer necessary, so we may as well save some cycles. @bparker06
> get rid of for loop and frame_buf

- src/Config.cpp
- src/Config.h
- src/NDS.cpp
- src/Wifi.cpp
- src/libretro/libretro.cpp
- src/libui_sdl/libui/ui.h
- src/libui_sdl/libui/unix/area.c
- src/libui_sdl/libui/unix/draw.c
- src/libui_sdl/libui/unix/drawmatrix.c
- src/libui_sdl/libui/unix/menu.c
- src/libui_sdl/libui/windows/area.cpp
- src/libui_sdl/libui/windows/area.hpp
- src/libui_sdl/libui/windows/areadraw.cpp
- src/libui_sdl/libui/windows/draw.cpp
- src/libui_sdl/libui/windows/menu.cpp
- src/libui_sdl/main.cpp
- src/melon_fopen.h
http://melonds.kuribo64.net/comments.php?id=36
> Update to melonDS 0.6

- src/libretro/libretro.cpp
> fix reset by loading rom after NDS reset

- src/NDS.cpp
- src/NDSCart.cpp
- src/Platform.h
- src/SPI.cpp
- src/libretro/libretro.cpp
Also removed all the previously hacked in paths for libretro since the Platform file functions *just* works now
This should also fix some files ending up in the wrong path
> Refactor Platform file functions to use vfs filestreams

- Makefile.common
- src/GPU2D.h
- src/SPI.cpp
- src/libretro/libretro-common/compat/compat_posix_string.c
Fixed compilation on MSVC, fixed crash when system directory containing bios files is non writable.
> Fixed MSVC compilation, start condition

- src/libretro/libretro.cpp
Lets you keep only the action screen up and switch on-the-fly when needed.
Also made the hw_render variable extern, because it wouldn't compile due to duplicate symbols.
> Add an extra controls shortcut to switch screens.

- Makefile
@twinaphex asked to send a PR if we came across these "GG NO RE" messages a while ago, so here you have it, one less! :p
> Remove useless echoes from Makefile.

- src/libretro/opengl.cpp
preparatory patch for https://github.com/libretro/RetroArch/pull/11368
> improve context request

- src/libretro/opengl.cpp
I can't find a previous version of that core that works with mesa drivers, it works with this fix.
I think the issues from https://github.com/libretro/melonDS/issues/57 are also related to this.
> melonDS wants opengl 3.1

- Makefile
First attempt at getting this working.
I basically copied the `unix` config and changed the `JIT_ARCH` and `HAVE_OPENGL`
> rpi4-aarch64: add section to Makefile

- src/NDS.cpp
- src/NDSCart.cpp
- src/NDSCart.h
Ported from upstream.
Fixes #79
> Fixes saving performance issues

- Makefile
Work great
Tested on all boards
> Add support on N2 / VIM3 / C4

- Makefile
Tested on RPI4 work very well.
That improve FPS too.
> Fix openGL on RPI4

- Makefile
Fix Spaces that create issue on N2 Build
> Fix MakeFile

- src/libretro/opengl.cpp
Brings OpenGL renderer hybrid mode in line with the software renderer. Also fixes up texture padding values to remove texture offset issues noted in https://github.com/libretro/melonDS/issues/99
> Fix hybrid screen layout for OpenGL renderer

- src/libretro/libretro.cpp
As suggested in #134, here is a new core option to randomize the MAC address.
> Add ability to randomize the MAC address

- src/libretro/libretro.cpp
Exposes the slot 2 functionality using the subsystem interface to load a gba rom along with an nds rom.
Tested succesfully with Daigassou! Band-Brothers and it's expansion, Castlevania Dawn of Sorrow with Aria of Sorrow and Advance Wars Dual Strike with both gba Advance Wars games. Each game detects the cart and does what its meant to.
I'm unable to test the Pokemon games two way communication as I dont have any games played far enough that transferring is possible. It should work as the correct save file paths for both roms are being passed to melonds, but I can't verify myself.
> Expose Slot 2 via subsystem interface.

- src/libretro/libretro.cpp
- src/libretro/utils.h
Adds Libretro Cheat Code Support so users could add emulator cheat code on top of retroarch cheat code
> feat(cheat): sets cheat as received in retro_cheat_set
